### ISSUE TITLE
Design Permission screens

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#441]
Existing permission screens need a design refinement pass, to bring them in line with our new designs. 

### Acceptance Criteria
- [x] Designs are accepted and ready for build

**Comment by beepdotgov** [comment]
@sknep @hursey013, I’ve got some initial designs for you to review! As always, [the designs are in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=736-5239&t=qyhrsyQDIsjFDT2n-0), and I’ve attached them below.

A couple quick highlights:

- Since we’re asking the user to (potentially) cycle repeatedly between the user management table and various forms, I think overlays could make for a nice UX solution here.
- These are widescreen-only for now, but they’ll adapt nicely to any breakpoint.
- At the risk of becoming That `<details>` Guy, I think the Access Permissions screen could benefit with a collapsible element that defines the various roles.

Once we’ve got an initial direction nailed down, I can adapt these for smaller screens, and also work in some error/update messages. But I wanted to see how these felt to you! What feels like it’s working well? What needs refinement?

(If you’d prefer to talk through these in person, say the word! I can find time on our calendars for early next week.)

<details>
<summary><strong>Mockups</strong></summary>

<h3>Organization roles:</h3>
<img width="1266" alt="Manage users — org roles" src="https://github.com/user-attachments/assets/734f3ac8-3178-476d-8534-f187497e1473">

<h3>Access permissions:</h3>
<img width="1266" alt="Manage users — access permissions" src="https://github.com/user-attachments/assets/22ba1845-f78b-4e4a-bb57-6906f17e5984">

<h3>Access permissions (with expanded definitions):</h3>
<img width="1266" alt="Manage users — access permissions (definitions expanded)" src="https://github.com/user-attachments/assets/8cb212d8-7c9f-4ece-bbf5-59790fbeafc0">

</details>

**Comment by sknep** [comment]
I love it. One thought is that the list of roles in the table should match the order that they are in the dropdown for people who are trying to read what each one is for... I know they're alphabetical in the dropdown but I think I like the order you've sorted them in the table better.

 I really adore this treatment. Thanks Ethan!

**Comment by beepdotgov** [comment]
@sknep, I am _delighted_ to hear this looks good to you!

> One thought is that the list of roles in the table should match the order that they are in the dropdown for people who are trying to read what each one is for... I know they're alphabetical in the dropdown

Oh, that’s a great catch, Sarah — thank you. I’ll do a quick editing pass on those definitions, and make sure they line up with the order in the table. Thanks again!

@hursey013, how’re things looking to you?

**Comment by beepdotgov** [comment]
Okay! Here’s some tweaked help text for roles on the Access Permissions overlay:

<img width="1266" alt="" src="https://github.com/user-attachments/assets/9a9b0d00-6db2-4956-9d61-a64c36306556">

(Also [available in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=771-7110&t=eGqUTpdhgXatTatU-0).)

@sknep, how’s that feel to you now?

@hursey013, let me know if you have any additional thoughts! Once this feels solid to both of you, I’ll work on some small screen-friendly layouts, and set up some error/update message styles.

**Comment by sknep** [comment]
This is great! BTW I often see an implied pattern in the use of multiple buttons together in USWDS where the secondary button is in the outline variant. Is that something you've considered? If you've thought about it and prefer the primary / base pair, I understand. I imagine this is one of many situations where Accept / Cancel action buttons are going to be proximate, so what you choose here can be extended elsewhere.

**Comment by hursey013** [comment]
@beepdotgov I love the use of overlays for this! As with our other modals/overlays I think the main a11y concern is making sure we get the focus state correct and trap focus within the overlay. Visually everything looks wonderful! My only (non-blocking) feedback would be that the collapsed `What do these roles mean?` isn't immediately identifiable as clickable to me. Maybe it's the less rounded borders or the color, but wanted to pass that along since I imagine we'll want to use similar collapsible `<Details />` panels elsewhere in the app.

**Comment by sknep** [comment]
I will have to gently disagree with brian that to me, the collapsed accordion looks _eminently_ clickable, between the underlined text, the button-ish treatment, and the caret :D however, that's just my reaction! If yall wanna keep working on that, I get it

**Comment by beepdotgov** [comment]
This is _excellent_ feedback all around. Thank you both! I’ve attached a couple updates below I could use your feedback on — namely,

1. Updated button styling
2. Updated collapsible styling
3. Error/success messages (with a bonus UX question I could use help on)
4. Small screen overlay layouts

As always, let me know if you’d like to discuss these in a call!

(And also as always, [the updated art is in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=846-9158&t=vGEJeMpAyVajEgLF-0), and attached below.)

## Button styling

@sknep, thanks so much for pulling out that USWDS guidance! Since this is taking place in an overlay, I think we could comfortably settle on either outlined _or_ solid? But that question aside, I rather like how the outlined version looks:

<img width="687" alt="Screenshot 2024-08-29 at 3 20 31 PM" src="https://github.com/user-attachments/assets/812df70f-0ced-4eee-ac75-8b7df09f8657">

What do you two think?

## Collapsible treatment

@hursey013 and I paired for a bit, and we settled on a style for our collapsibles a little more accordion-y, which could potentially extend to other parts of our UI.

### Closed/default

<img width="539" alt="Screenshot 2024-08-29 at 3 22 23 PM" src="https://github.com/user-attachments/assets/53b9bab3-fc8d-4992-bf10-f06a1de6a282">

### Expanded

<img width="548" alt="Screenshot 2024-08-29 at 3 23 28 PM" src="https://github.com/user-attachments/assets/1b81020f-12fc-44b1-8e91-447213d1e54c">

I agree with Sarah, that the original version had a nice CTA-ish feel. At the same time, I think this version works a bit better? It’s still noticeable, but it feels less dominant in context: it doesn’t draw too much attention/focus from other nearby (and more important) elements. But I’d love to hear what you think!

## Alert/update messages

I’ve also included some styling for alert and error messages. My hope is that they’ll work well not just in the overlays, but also throughout the UI. Let me know what you think!

That said, I have one **UX question for both of you:** when an overlay form submits successfully, do we:

1. close the overlay automatically, and display the success message on the “parent” page?
2. keep the overlay open, and display the success message in the overlay?

Generally, I’d recommend option 1. But if there’s a cloud.gov case for letting the user continue to work in the overlay, let me know!

## Small screen layouts

I’ve adapted the overlay layouts for smaller screens — would love any thoughts you might have!

---

<details>
<summary><strong>Mockups</strong></summary>

<h2>Update organization roles</h2>

<img width="1266" alt="Manage users — update org roles" src="https://github.com/user-attachments/assets/10c594a6-4e91-4ba7-b966-cb8b3e60da7d">

<h2>Update access permissions</h2>

<h3>Collapsible closed</h3>
<img width="1266" alt="Manage users — update access permissions" src="https://github.com/user-attachments/assets/d297d687-c3aa-40ca-a80c-3260b0fed320">

<h3>Collapsible open</h3>
<img width="1266" alt="Manage users — update access permissions (terms expanded)" src="https://github.com/user-attachments/assets/509ef7bb-bb22-411d-ad50-04caf54622d2">

<h3>Success+error messages</h3>
<img width="1266" alt="Manage users — success+error messages" src="https://github.com/user-attachments/assets/701afb0b-8f1a-4cc2-a569-cab4f068f873">

<h2>Small screen layouts</h2>

<h3>Update organization roles (small screen)</h3>
<img width="398" alt="Manage users — update organization roles (small screen)" src="https://github.com/user-attachments/assets/eff7a5b6-06ab-43f7-aca1-198892c2eb7b">

<h3>Update access permissions (small screen)</h3>
<img width="398" alt="Manage users — update access permissions (small screen)" src="https://github.com/user-attachments/assets/35f87e62-ac5e-4c5d-8c6b-bd477f7422d5">

<h3>Update access permissions (small screen, terms expanded)</h3>
<img width="398" alt="Manage users — update access permissions (small screen, terms expanded))" src="https://github.com/user-attachments/assets/44d9980e-8204-44f3-9fcf-4fa8e0ef16ef">
</details>

**Comment by beepdotgov** [comment]
Quick update from Slack: we did a quick refinement pass on the collapsible to brighten it up a bit.

![collapsed](https://github.com/user-attachments/assets/4f441283-1857-44c5-b091-c87ab7b631b1)
![expanded](https://github.com/user-attachments/assets/781f9434-1f7d-4232-8e67-361743b8fbed)

([Figma’s been updated](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=846-9158&node-type=SECTION&t=QWEt3FjrC4neDaRg-0) as well.)

**Comment by hursey013** [comment]
@beepdotgov I think since the form allows folks to make several selections (selecting various checkboxes) prior to submitting, I think they will be able to accomplish everything in one submit action. Given that, I agree closing the overlay and then displaying the message within the context of the main page is the way to go (ideally moving focus to it when the overlay closes).

**Comment by beepdotgov** [comment]
Sounds great, @hursey013 — thank you! We’ll plan on closing the overlays on a successful form submission.

Just to check: any other design notes from you or @sknep, or can we consider these ready for implementation?

**Comment by hursey013** [comment]
Looks great to me! @sknep is out today, so let's move forward with these designs to keep things moving and we can do a follow up PR to address any additional tweaks @sknep may have. Overall though, these are ready to move to implementation! Thank you!

**Comment by beepdotgov** [comment]
_Wonderful._ Thanks, Brian! Excited to move these forward.

@echappen, I’ll get Figma prepped for handoff; would it be possible to do a feasibility review next week?

**Comment by echappen** [comment]
@beepdotgov certainly! I'll put something on the calendar

**Comment by beepdotgov** [comment]
Figma’s ready for tomorrow’s discussion: [artwork’s here](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=225-1420&node-type=CANVAS&t=sKxFV2vucZDrnucM-0)!

**Comment by beepdotgov** [comment]
Marking as done now that we’ve had our feasibility review, and #468 has been opened. Onward! 🚀

**Comment by mogul** [comment]
I'm late with this feedback, sorry: 

> Managers can do everything Developers can do [...]

[SpaceManagers **cannot** do everything that the other roles can do.](https://docs.cloudfoundry.org/concepts/roles.html#permissions) This is a common misconception that comes up a lot; people frequently forget that they need both the SpaceManager and the SpaceDeveloper role to manage both users and apps in a space.

**Comment by beepdotgov** [comment]
Thank you very much for catching that, @mogul — much, much appreciated, and we definitely want to get that language right.

If we dropped that “can do everything” clause, and swapped in something like this:

> Managers administer Spaces, which allows them to manage users, and to enable features.

Would that be more accurate/appropriate, do you think?

(cc @hursey013, #468)

**Comment by hursey013** [comment]
@beepdotgov The best reference for this is https://docs.cloudfoundry.org/concepts/roles.html. I think the only potentially confusing aspect is that only org managers can create spaces. Space manager appears to be able to edit and rename a space, but as already noted, no ability to create or `Deploy, run, and manage apps`.

**Comment by mogul** [comment]
Yes, that's better. You could also leave a link to the docs in there to find exact details.

**Comment by beepdotgov** [comment]
@hursey013, thanks so much for that note; @mogul, I really like the suggestion to link out to the docs. (I think there’s only so much summarization we can do here, anyway.)

Here’s another quick riff:

<img width="537" alt="image" src="https://github.com/user-attachments/assets/2c27efa1-256c-4c29-a12e-30c9dc307165">

<details>
<summary>Here’s the revised text:</summary>
<p>Here’s a brief overview:</p>

<ul>
<li><strong>Developers</strong> can create and manage apps and services. They can also view logs, reports, and settings for a Space.
<li><strong>Supporters</strong> can troubleshoot and debug a Space’s apps and service bindings.
<li><strong>Auditors</strong> can view logs, reports, and settings for a Space.
<li><strong>Managers</strong> can view and edit Spaces, which allows them to manage users, and to enable features.
</ul>

<p>Our <a href="#">documentation</a> has more detailed information about these roles. (And if you have more questions, please contact us at <a href="#">support@cloud.gov</a>.)</p>
</details>

Does that feel more accurate? Once this looks good, I’ll update the designs, and work to get this into the prototype.

**Comment by mogul** [comment]
Yes, although unfortunately it's not "our" documentation, in that it doesn't live under the cloud.gov domain/ownership.

**Comment by beepdotgov** [comment]
Oh, good catch — thanks again, @mogul. Let’s go with “The documentation”, then?

<img width="518" alt="image" src="https://github.com/user-attachments/assets/2ba0991f-0259-4f2e-8972-cddf153c2b60">

**Comment by mogul** [comment]
SGTM!

**Comment by beepdotgov** [comment]
[Updated Figma](https://github.com/cloud-gov/cg-ui/issues/97#:~:text=Figma%E2%80%99s%20been%20updated), and pinged https://github.com/cloud-gov/cg-ui/issues/97#issuecomment-2344622702 for implementation.

@mogul Thank you again for catching this! Seriously, the feedback is a massive help, and I really appreciate you taking the time to review some copy changes.
