### ISSUE TITLE
If a user is unauthenticated and attempts to visit an authenticated page, redirect them to UAA

### ISSUE THREAD

**Issue by hursey013** [cloud-gov/cg-ui#494]
Right now when folks are not logged in and attempt to visit a page of the app such as `/orgs` they will be presented with an error message:

![Screenshot 2024-09-13 at 12 17 32 PM](https://github.com/user-attachments/assets/4287a6ef-f656-4525-8096-d470adf362ce)

Instead, users should be redirected to the login flow via UAA, and once authenticated, returned to the page they were attempting to access.

### Acceptance Criteria
- [ ] Visiting an authenticated page while unauthenticated will redirect you to login flow
- [ ] Upon successfully logging in, user is redirect to the page they were previously attempting to access

**Comment by echappen** [comment]
@hursey013 
> Upon successfully logging in, user is redirect to the page they were previously attempting to access

I don't see any [UAA parameter](https://docs.cloudfoundry.org/api/uaa/version/77.16.0/index.html#authorization-code-grant) for this. But, since we have a callback url where we set the auth token, we could:
1) in the `/login` middleware routine, try setting a browser cookie with the desired page path, then 
2) redirect to that path at the end of the `/auth/login/callback` middleware routine if that cookie is present. 

This would be a similar to how we handle our `state` cookie, where we set it at the beginning of login and check it in the callback. Does this sound like a good approach?
