### ISSUE TITLE
Design “all organizations” page

### ISSUE THREAD

**Issue by beepdotgov** [cloud-gov/cg-ui#514]
Per increment planning, we decided to establish an updated design for the “all organizations” page, which will be accessible through the Dashboard’s org picker. (#409)

One outcome of this work might be a reusable component that could also be adapted for a similar “list of things” page, such as the Dashboard’s applications page.

_Can this task be done in one increment?_

Yes.

### Acceptance Criteria
- [x] Designs are accepted by cloud.gov
- [x] Designs have been reviewed for technical feasibility, and handed off for implementation

**Comment by beepdotgov** [comment]
@sknep @hursey013 Got an initial design attached below! (And [in Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1205-42366&node-type=section&t=gqzEqw3wlpCuDBlR-0), as ever.)

Two things while you look into this:

- From [an earlier discussion in Slack](https://gsa-tts.slack.com/archives/C065GC3R139/p1722527012760029), it sounds like this page won’t have to deal with wild amounts of density. That’s a big reason I decided to go with this card-driven layout, rather than a more tabular approach. (It also lets us reuse the “welcome mat” pattern we just finalized!)
- I thought the individual cards could highlight a couple key pieces of information: the number of users and applications, the user’s role in that org, and memory usage. But I’d love to hear how this feels to you; is there more/different information we need here?

Thanks, both! Excited to hear what you think.

**Comment by hursey013** [comment]
Wow @beepdotgov, just wow 😍  Your choices on which pieces of information to include within the cards are spot on in my opinion. I think the only thing perhaps to make more clear would be that the memory represents the current _allocation_ of memory to the org as opposed to a live snapshot of the current memory usage. For example an org might currently have 10GB of available memory and have only allocated 6GB of that to the various apps within the org, leaving 4GB remaining to be allocated. Maybe that's already your intent, but at first glance I interpreted the green/red gauges to indicate live usage (since that's what you often see in dashboard like this).

What do you think about including the org picker on pages like this? I think in my head I've envisioned that dropdown being a consistent part of the UI while in the platform section, but perhaps that's redundant here?

**Comment by beepdotgov** [comment]
@hursey013, I’m _delighted_ this feels like the right direction! Seriously, thanks for that, and for the feedback!

> I think the only thing perhaps to make more clear would be that the memory represents the current allocation of memory to the org as opposed to a live snapshot of the current memory usage.

I didn’t realize Stratos was displaying _memory available for allocation_, so thank you VERY much for calling that out.

Just curious, would it make more sense if we swap out “allocated” for “used”, like this:

<img width="415" alt="image" src="https://github.com/user-attachments/assets/a658a783-3d5d-4532-94b3-e98016417e87">

Would that feel more accurate?

> What do you think about including the org picker on pages like this? I think in my head I've envisioned that dropdown being a consistent part of the UI while in the platform section, but perhaps that's redundant here?

Oh, that’s a really interesting idea! I think we _could_ include it, but we’d need to revise its design a bit: namely, we’d need a default “No organization selected” state. At least as we’ve currently defined it, the picker shows the currently active org, with some links to move to another organization:

<img width="520" alt="image" src="https://github.com/user-attachments/assets/94b7df47-a5b1-4a1d-929c-17c6e6f5c572">

But on _this_ page, we don’t have an “active” organization. (Which is why I removed it!) But if we want to include it here, I think we could make it work — let me know, and I’ll tinker with some options for round 2.

**Comment by beepdotgov** [comment]
Okay, round two! [In Figma](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1250-47200&node-type=section&t=ZLMoFkmpZTjp3oGR-0), but also: right here!

<img width="1266" alt="View organizations(1)" src="https://github.com/user-attachments/assets/509dc368-65ba-4852-9eb2-5199a861b5b9">

I’ve tweaked the label on the memory bar, and changed “Current organization” to “Organization”, which allows us to have an empty state on this page. Expanded, it’d work the same, but we’d remove the “View all organizations” link like so:

<img width="598" alt="image" src="https://github.com/user-attachments/assets/bc4b0d1d-ba10-4650-983e-e5aae575274b">

@hursey013 Would love to hear what you think!

**Comment by hursey013** [comment]
Apologies for the delayed response @beepdotgov! I think `allocated` works well here, and not to backtrack, but seeing the org picker with the empty state like that on this page makes it feel almost unnecessary, especially on this page since users have a clear path to picking an organization via the cards. Unless you have a strong opinion one way or the other I'd say we can leave the org picker off this page as you originally proposed. Otherwise, this looks great, lets move on to feasibility/implementation! Thank you @beepdotgov

**Comment by beepdotgov** [comment]
Thank _you_, @hursey013! I think that’s the right call: I’ve dropped the org picker, and updated the design.

<img width="1266" alt="View organizations" src="https://github.com/user-attachments/assets/cec2c836-6403-49ce-a983-e1f78e3f4c67">

I’ve pulled together a small screen-friendly view of the design as well:

https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1319-21282&node-type=section&t=E168n49EPnTe4Ef3-0

@echappen, just noting that these are ready for feasibility/implementation! Onward! 🎉🚀

**Comment by beepdotgov** [comment]
Feasibility review with @echappen is done, and #539 is open, so closing this out! Onward! 🚀
