### ISSUE TITLE
Implement "all organizations" page

### ISSUE THREAD

**Issue by echappen** [cloud-gov/cg-ui#539]
Similar design elements to #514 so coordinate with @cannandev on shared components

[Figma widescreen](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1398-30454&m=dev)
[Figma small screen](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1398-30906&m=dev)

### Acceptance Criteria
- [x] alpha order for organizations
- [x] orange is 75%, red is 90%
- [ ] bust all caching for that page, add back caching as needed

**Comment by beepdotgov** [comment]
@echappen Oh, great catch — thanks, Eleni.

I’d like to hear what @hursey013 says on the business rules front, because I could see two possible scenarios:

- If this would be considered an error from Cloud.gov’s standpoint, I think we’d want to suppress the progress bar, and note the error on the card. (Like, just e.g., with a prompt to contact support.)
- If this isn’t an error, and happens occasionally with Cloud.gov’s clients, I think we could simply suppress the progress bar entirely.

Brian, let me know what you think? I can mock up whichever option feels right for Cloud. (Or both options, if need be!)

**Comment by hursey013** [comment]
Interesting! Given the way the IAAs are written I believe every customer should have an assigned memory quota in production, but I could see perhaps some internal facing cloud.gov orgs or experimental orgs in dev having a null value. I'd say in those cases we could either suppress the progress bar, or better yet could we illustrate that there is no limit set with a `∞` symbol on the upper limit so it's clear there is no limit?

**Comment by hursey013** [comment]
I think this looks great, thanks @beepdotgov!

**Comment by beepdotgov** [comment]
_Wonderful_, thanks @hursey013!

@echappen, I’ve [updated Figma showing a card with this state](https://www.figma.com/design/DNbFdd7YrA2MpgeXNgmNLz/Cloud.gov-%E2%80%94-Dashboard-UI-redesign?node-id=1319-21282&t=rthkcdRxoBchcbc1-4), but let me know if you need anything else from me!

**Comment by echappen** [comment]
Looks great @beepdotgov, thank you both! I'll start implementing this.

**Comment by hursey013** [comment]
> Sorry to bring this up again: "24MB allocated; no upper limit" - the 24MB figure here is coming from [the usage summary endpoint](https://v3-apidocs.cloudfoundry.org/version/3.167.0/index.html#get-usage-summary) and represents actual usage. May I change "allocated" to "used" here? (just for instances with no upper limit)

Yes, that makes sense to me @echappen!

**Comment by beepdotgov** [comment]
Ach yes, sorry — after our memory conversation last week, I think I forgot to update that. (The jokes, they write themselves.)

I’ll update Figma as well, to make sure those cards say “used” rather than “allocated”.
